### ISSUE TITLE
Cant find the Documentation

### ISSUE THREAD

**Issue by Xhenet** [mediagoom/node-play#5]
Hi, can someone help me to find the documentation, I can't find it. I want to upload a video with the API and encode it, to then use the API to get the stream back.

**Comment by aseduto** [comment]
Hi Xhenet,
At the moment the api are not yet documented.

You can look at src/server/app.js to see them if you want to use web api.

Basically you will have to call /api/upload/:name to get an id for your upload.
Then chunk your file and call put on /upload/:id? to perform the upload.

When the upload end the encoding and mixing of the file will start automatically.

You can call /api/queue/:id to get the status of your file. Or /api/queue/status/:id to get the list and status of all the operations the system is performing.

Let me know if this help you.

**Comment by Xhenet** [comment]
Hi, thanks, that helped a lot to understand how it works.

Once I uploaded the file successfully, how can I play them back with HLS or MPEG-DASH?

**Comment by aseduto** [comment]
Hi Xhenet,
Once your file is ready you have an hls link and an MPEG-DASH link.
You get the links from /api/status/:id

Using [mediagoom/Play](https://github.com/mediagoom/Play) you can play it like this:

this.status = response.data.status;
      this.owner = response.data.owner;
      this.dash = response.data.dash;
      this.hls3 = response.data.hls3;
      this.thumb = response.data.thumb;
      this.id = response.data.id;
      this.name = response.data.name;
      mgp.play(window.location.protocol + '//' + window.location.host + '/play/' + this.owner + '/' + this.id + '/', response.data);

Where window.location is the node-play url and response.data is the response from 
/api/status.

**Comment by Xhenet** [comment]
Thanks for all the help until now, may I ask another question, I got the video encoding to work, and when I access /api/status/:id I get objects like this one:
{
        previous: [
        "reserved"
        ],
        status: "ok",
        name: "SampleVideo_1280x720_5mb_mp4",
        id: "002546930855_SampleVideo_1280x720_5mb_mp4",
        owner: "uploader",
        datetime: "2019-04-16T14:12:28.410Z",
        creationtime: "2019-04-16T14:12:24.680Z",
        queue_id: "002546930852-0001",
        hls3: "STATIC/main.m3u8",
        dash: "STATIC/index.mpd",
        thumb: [
        "img001.jpg",
        "img002.jpg",
        "img003.jpg",
        "img004.jpg"
        ],
        hls4: null,
        playready: null,
        widevine: null
        }

I then imported mgp with var mgp = require('mgplay'); but when I run mgp.play('http://localhost:3000/play/uploader/002546930855_SampleVideo_1280x720_5mb_mp4/', response.data); in my express app I get the error message ReferenceError: window is not defined

**Comment by aseduto** [comment]
Hi Xhenet,

mediagoom/play has a peer dependency from dash.

Make sure you reference the following before mgplay:

<script crossorigin src="https://unpkg.com/dashjs@2.9.0/dist/dash.mediaplayer.min.js"></script>

**Comment by Xhenet** [comment]
Ok, I got it to work now, thanks for all the help.
