### ISSUE TITLE
How can I define the quality of the output video after conversion. 

### ISSUE THREAD

**Issue by Xhenet** [mediagoom/node-play#6]
Is there a way to dynamically set the video Quality besides changing it for every video in src/flows/encode.js by adding another generate_config_encode(...)

**Comment by aseduto** [comment]
Hi Xhenet,
You would like to produce different bitrates than what is producing now?
Right now the only way is to change the current code.
The plan would be to have a configurable input from which to generate the final flow of operations.

**Comment by Xhenet** [comment]
Ok, thanks.
